const LETTER_NUMBER = 4;
const GUESS_NUMBER = 6;
const WORDS = [
    "aahs",
    "abbe",
    "abbr",
    "abed",
    "abet",
    "able",
    "ably",
    "abut",
    "acct",
    "aced",
    "aces",
    "ache",
    "achy",
    "acid",
    "aclu",
    "acme",
    "acne",
    "acre",
    "acts",
    "adam",
    "adds",
    "adit",
    "ados",
    "advt",
    "aeon",
    "aery",
    "afar",
    "afro",
    "agar",
    "aged",
    "ages",
    "agha",
    "agin",
    "agog",
    "ague",
    "ahem",
    "ahoy",
    "aide",
    "aids",
    "ails",
    "aims",
    "airs",
    "airy",
    "ajar",
    "akin",
    "alai",
    "alan",
    "alar",
    "alas",
    "alba",
    "albs",
    "alee",
    "ales",
    "alfa",
    "alga",
    "alii",
    "alit",
    "alls",
    "ally",
    "alma",
    "alms",
    "aloe",
    "alps",
    "also",
    "alto",
    "alum",
    "amah",
    "amen",
    "amex",
    "amid",
    "amis",
    "ammo",
    "amok",
    "amps",
    "amyl",
    "anal",
    "ands",
    "anew",
    "anis",
    "ankh",
    "anna",
    "anne",
    "anno",
    "anon",
    "ansi",
    "ante",
    "anti",
    "ants",
    "anus",
    "aped",
    "aper",
    "apes",
    "apex",
    "apse",
    "aqua",
    "arab",
    "arch",
    "arco",
    "arcs",
    "area",
    "ares",
    "aria",
    "arid",
    "arks",
    "arms",
    "army",
    "arse",
    "arts",
    "arty",
    "arum",
    "asap",
    "asea",
    "ashy",
    "asia",
    "asks",
    "asps",
    "assn",
    "asst",
    "atma",
    "atom",
    "atop",
    "attn",
    "atty",
    "auks",
    "auld",
    "aunt",
    "aura",
    "auto",
    "avdp",
    "aver",
    "aves",
    "avid",
    "avis",
    "avow",
    "away",
    "awed",
    "awes",
    "awls",
    "awns",
    "awol",
    "awry",
    "axed",
    "axel",
    "axes",
    "axil",
    "axis",
    "axle",
    "axon",
    "ayah",
    "ayes",
    "baal",
    "baas",
    "baba",
    "babe",
    "babu",
    "baby",
    "bach",
    "back",
    "bade",
    "bads",
    "bags",
    "baht",
    "bail",
    "bait",
    "bake",
    "bald",
    "bale",
    "bali",
    "balk",
    "ball",
    "balm",
    "band",
    "bane",
    "bang",
    "bank",
    "bans",
    "barb",
    "bard",
    "bare",
    "barf",
    "bark",
    "barn",
    "bars",
    "base",
    "bash",
    "bask",
    "bass",
    "bast",
    "bate",
    "bath",
    "bats",
    "baud",
    "bawd",
    "bawl",
    "bays",
    "bdrm",
    "bead",
    "beak",
    "beam",
    "bean",
    "bear",
    "beat",
    "beau",
    "beck",
    "beds",
    "beef",
    "been",
    "beep",
    "beer",
    "bees",
    "beet",
    "begs",
    "bell",
    "belt",
    "bema",
    "bend",
    "bene",
    "bens",
    "bent",
    "berg",
    "berm",
    "bess",
    "best",
    "beta",
    "bete",
    "bets",
    "bevy",
    "beys",
    "bias",
    "bibs",
    "bide",
    "bids",
    "bier",
    "biff",
    "bike",
    "bile",
    "bilk",
    "bill",
    "bind",
    "bins",
    "biol",
    "bios",
    "bird",
    "bite",
    "bits",
    "blab",
    "blah",
    "blat",
    "bldg",
    "bled",
    "blew",
    "blip",
    "blob",
    "bloc",
    "blot",
    "blow",
    "blue",
    "blur",
    "blvd",
    "boar",
    "boas",
    "boat",
    "bobs",
    "boca",
    "bock",
    "bode",
    "bods",
    "body",
    "boer",
    "boff",
    "bogs",
    "bogy",
    "boil",
    "bola",
    "bold",
    "bole",
    "boll",
    "bolo",
    "bolt",
    "bomb",
    "bona",
    "bond",
    "bone",
    "bong",
    "bono",
    "bons",
    "bony",
    "boob",
    "book",
    "boom",
    "boon",
    "boor",
    "boos",
    "boot",
    "bops",
    "bore",
    "born",
    "bort",
    "bosh",
    "boss",
    "both",
    "bout",
    "bowl",
    "bows",
    "boxy",
    "boyo",
    "boys",
    "bozo",
    "brad",
    "brae",
    "brag",
    "bran",
    "bras",
    "brat",
    "braw",
    "bray",
    "bred",
    "brew",
    "brie",
    "brig",
    "brim",
    "brin",
    "brio",
    "brit",
    "bros",
    "brow",
    "brut",
    "bubo",
    "bubs",
    "buck",
    "buds",
    "buff",
    "bugs",
    "bulb",
    "bulk",
    "bull",
    "bump",
    "bums",
    "bund",
    "bung",
    "bunk",
    "bunn",
    "buns",
    "bunt",
    "buoy",
    "burg",
    "burl",
    "burn",
    "burp",
    "burr",
    "burs",
    "bury",
    "bush",
    "buss",
    "bust",
    "busy",
    "buts",
    "butt",
    "buys",
    "buzz",
    "byes",
    "byre",
    "byte",
    "cabs",
    "cads",
    "cafe",
    "cage",
    "cagy",
    "cake",
    "caky",
    "calc",
    "calf",
    "calk",
    "call",
    "calm",
    "calx",
    "came",
    "camp",
    "cams",
    "cane",
    "cans",
    "cant",
    "cape",
    "caps",
    "card",
    "care",
    "carl",
    "carp",
    "cars",
    "cart",
    "casa",
    "case",
    "cash",
    "cask",
    "cast",
    "cats",
    "caul",
    "cave",
    "cavy",
    "caws",
    "cays",
    "ceca",
    "cede",
    "cees",
    "ceil",
    "cell",
    "celt",
    "cent",
    "cert",
    "cess",
    "chad",
    "cham",
    "chap",
    "char",
    "chat",
    "chaw",
    "chef",
    "chem",
    "chew",
    "chez",
    "chia",
    "chic",
    "chid",
    "chin",
    "chip",
    "chit",
    "chop",
    "chou",
    "chow",
    "chub",
    "chug",
    "chum",
    "ciao",
    "cine",
    "circ",
    "cite",
    "city",
    "clad",
    "clam",
    "clan",
    "clap",
    "claw",
    "clay",
    "clef",
    "clew",
    "clip",
    "clod",
    "clog",
    "clop",
    "clot",
    "cloy",
    "club",
    "clue",
    "cmdg",
    "coal",
    "coat",
    "coax",
    "cobs",
    "cock",
    "coco",
    "coda",
    "code",
    "cods",
    "coed",
    "cogs",
    "coho",
    "coif",
    "coil",
    "coin",
    "coir",
    "coke",
    "cola",
    "cold",
    "cole",
    "coll",
    "colt",
    "coma",
    "comb",
    "come",
    "comp",
    "cone",
    "conf",
    "conj",
    "conk",
    "conn",
    "cons",
    "cont",
    "cony",
    "cook",
    "cool",
    "coon",
    "coop",
    "coos",
    "coot",
    "cope",
    "cops",
    "copy",
    "cord",
    "core",
    "cork",
    "corm",
    "corn",
    "corp",
    "cosh",
    "cost",
    "cosy",
    "cote",
    "cots",
    "coup",
    "cove",
    "cowl",
    "cows",
    "cozy",
    "crab",
    "crag",
    "cram",
    "crap",
    "craw",
    "cree",
    "crew",
    "crib",
    "crop",
    "crow",
    "crud",
    "crux",
    "ctrl",
    "cuba",
    "cube",
    "cubs",
    "cuds",
    "cued",
    "cues",
    "cuff",
    "cuke",
    "cull",
    "cult",
    "cunt",
    "cups",
    "curb",
    "curd",
    "cure",
    "curl",
    "curs",
    "curt",
    "cusp",
    "cuss",
    "cute",
    "cuts",
    "cyan",
    "cyme",
    "cyst",
    "czar",
    "dabs",
    "dace",
    "dada",
    "dado",
    "dads",
    "daft",
    "dago",
    "dais",
    "dale",
    "dame",
    "damn",
    "damp",
    "dams",
    "dana",
    "dane",
    "dang",
    "dank",
    "dare",
    "dark",
    "darn",
    "dart",
    "dash",
    "data",
    "date",
    "daub",
    "dave",
    "dawn",
    "days",
    "daze",
    "dbms",
    "dead",
    "deaf",
    "deal",
    "dean",
    "dear",
    "debs",
    "debt",
    "deck",
    "deco",
    "deed",
    "deem",
    "deep",
    "deer",
    "dees",
    "deft",
    "defy",
    "deja",
    "dele",
    "deli",
    "dell",
    "demo",
    "dens",
    "dent",
    "deny",
    "dept",
    "derm",
    "desk",
    "deus",
    "deux",
    "deva",
    "dews",
    "dewy",
    "dhow",
    "diag",
    "dial",
    "diam",
    "dias",
    "dibs",
    "dice",
    "dick",
    "dict",
    "dido",
    "didy",
    "died",
    "diem",
    "dies",
    "diet",
    "digs",
    "dike",
    "dill",
    "dime",
    "dims",
    "dine",
    "ding",
    "dins",
    "dint",
    "dips",
    "dipt",
    "dire",
    "dirk",
    "dirt",
    "disc",
    "dish",
    "disk",
    "diva",
    "dive",
    "djin",
    "dock",
    "docs",
    "dodo",
    "doer",
    "does",
    "doff",
    "doge",
    "dogs",
    "dogy",
    "dojo",
    "dole",
    "doll",
    "dolt",
    "dome",
    "doms",
    "dona",
    "done",
    "dong",
    "dons",
    "doom",
    "door",
    "dope",
    "dopy",
    "dorm",
    "dorp",
    "dors",
    "dory",
    "dose",
    "doss",
    "dost",
    "dote",
    "doth",
    "dots",
    "doty",
    "dour",
    "dove",
    "down",
    "dows",
    "doxy",
    "doze",
    "dozy",
    "drab",
    "drag",
    "dram",
    "drat",
    "draw",
    "dray",
    "dreg",
    "drek",
    "drew",
    "drib",
    "drip",
    "drop",
    "drub",
    "drug",
    "drum",
    "drys",
    "duad",
    "dual",
    "dubs",
    "duce",
    "duck",
    "duct",
    "dude",
    "duds",
    "duel",
    "dues",
    "duet",
    "duff",
    "dugs",
    "duke",
    "dull",
    "duly",
    "dumb",
    "dump",
    "dune",
    "dung",
    "dunk",
    "duns",
    "duos",
    "dupe",
    "durn",
    "dusk",
    "dust",
    "duty",
    "dyad",
    "dyed",
    "dyer",
    "dyes",
    "dyke",
    "dyne",
    "each",
    "earl",
    "earn",
    "ears",
    "ease",
    "east",
    "easy",
    "eats",
    "eaux",
    "eave",
    "ebbs",
    "ebon",
    "eccl",
    "echo",
    "ecol",
    "econ",
    "ecru",
    "ecus",
    "edam",
    "edda",
    "eddy",
    "eden",
    "edge",
    "edgy",
    "edit",
    "eels",
    "eely",
    "eery",
    "effs",
    "efts",
    "egad",
    "eggs",
    "egis",
    "egos",
    "eire",
    "eked",
    "ekes",
    "elan",
    "elds",
    "elhi",
    "elks",
    "ells",
    "elms",
    "elmy",
    "else",
    "emir",
    "emit",
    "emmy",
    "emus",
    "encl",
    "ends",
    "engr",
    "enow",
    "envy",
    "eons",
    "epee",
    "epic",
    "eras",
    "erat",
    "ergo",
    "ergs",
    "erie",
    "erin",
    "erne",
    "erns",
    "eros",
    "errs",
    "erst",
    "eses",
    "espy",
    "esse",
    "etch",
    "etna",
    "etym",
    "even",
    "ever",
    "eves",
    "evil",
    "ewer",
    "ewes",
    "exam",
    "exec",
    "exes",
    "exit",
    "expo",
    "eyed",
    "eyer",
    "eyes",
    "face",
    "fact",
    "fade",
    "fads",
    "fags",
    "fail",
    "fain",
    "fair",
    "fait",
    "fake",
    "fall",
    "fame",
    "fang",
    "fans",
    "fare",
    "farm",
    "faro",
    "fart",
    "fast",
    "fate",
    "fats",
    "faun",
    "faut",
    "faux",
    "fawn",
    "fays",
    "faze",
    "fear",
    "feat",
    "feds",
    "feed",
    "feel",
    "fees",
    "feet",
    "fell",
    "felt",
    "fend",
    "fens",
    "fern",
    "fess",
    "feta",
    "fete",
    "feud",
    "fiat",
    "fibs",
    "fica",
    "fide",
    "fido",
    "fids",
    "fief",
    "fife",
    "figs",
    "fiji",
    "file",
    "fill",
    "film",
    "find",
    "fine",
    "fink",
    "finn",
    "fins",
    "fire",
    "firm",
    "firs",
    "fish",
    "fist",
    "fits",
    "five",
    "fixe",
    "fizz",
    "flab",
    "flag",
    "flak",
    "flan",
    "flap",
    "flat",
    "flaw",
    "flax",
    "flay",
    "flea",
    "fled",
    "flee",
    "flew",
    "flex",
    "flip",
    "flit",
    "floe",
    "flog",
    "flop",
    "flow",
    "flub",
    "flue",
    "flus",
    "flux",
    "foal",
    "foam",
    "fobs",
    "foci",
    "foes",
    "fogs",
    "fogy",
    "foil",
    "fold",
    "folk",
    "fond",
    "font",
    "food",
    "fool",
    "foot",
    "fops",
    "fora",
    "ford",
    "fore",
    "fork",
    "form",
    "fort",
    "foul",
    "four",
    "fowl",
    "foxy",
    "frag",
    "frat",
    "frau",
    "fray",
    "fred",
    "free",
    "fret",
    "frig",
    "friz",
    "frog",
    "from",
    "frow",
    "frug",
    "fuck",
    "fuds",
    "fuel",
    "fugs",
    "fuji",
    "full",
    "fume",
    "fumy",
    "fund",
    "funk",
    "furl",
    "furs",
    "fury",
    "fuse",
    "fuss",
    "fuze",
    "fuzz",
    "gabs",
    "gads",
    "gaff",
    "gaga",
    "gage",
    "gags",
    "gain",
    "gait",
    "gala",
    "gale",
    "gall",
    "gals",
    "game",
    "gams",
    "gamy",
    "gang",
    "gaol",
    "gape",
    "gaps",
    "gapy",
    "garb",
    "gars",
    "gary",
    "gash",
    "gasp",
    "gate",
    "gats",
    "gaud",
    "gave",
    "gawk",
    "gays",
    "gaze",
    "gear",
    "geed",
    "geek",
    "gees",
    "geld",
    "gels",
    "gelt",
    "gems",
    "gene",
    "gens",
    "gent",
    "geog",
    "geol",
    "geom",
    "germ",
    "gets",
    "geum",
    "ghat",
    "ghee",
    "gibe",
    "gibs",
    "gift",
    "gigs",
    "gila",
    "gild",
    "gill",
    "gilt",
    "gimp",
    "gins",
    "gips",
    "gird",
    "girl",
    "girt",
    "gist",
    "give",
    "glad",
    "glee",
    "glen",
    "glib",
    "glim",
    "glob",
    "glom",
    "glop",
    "glow",
    "glue",
    "glum",
    "glut",
    "gnat",
    "gnaw",
    "gnus",
    "goad",
    "goal",
    "goat",
    "gobs",
    "goby",
    "gods",
    "goer",
    "goes",
    "gogo",
    "gold",
    "golf",
    "gone",
    "gong",
    "good",
    "goof",
    "gook",
    "goon",
    "goop",
    "goos",
    "gore",
    "gory",
    "gosh",
    "goth",
    "gout",
    "govt",
    "gown",
    "goys",
    "grab",
    "grad",
    "gram",
    "gras",
    "gray",
    "grew",
    "grey",
    "grid",
    "grim",
    "grin",
    "grip",
    "grit",
    "grog",
    "grot",
    "grow",
    "grub",
    "guam",
    "guar",
    "guck",
    "guff",
    "gulf",
    "gull",
    "gulp",
    "gums",
    "gung",
    "gunk",
    "guns",
    "guru",
    "gush",
    "gust",
    "guts",
    "guys",
    "gyms",
    "gyps",
    "gyre",
    "gyro",
    "gyve",
    "hack",
    "hadj",
    "haft",
    "hags",
    "hahs",
    "hail",
    "hair",
    "haji",
    "hajj",
    "hake",
    "hale",
    "half",
    "hall",
    "halo",
    "halt",
    "hams",
    "hand",
    "hang",
    "hank",
    "haps",
    "hard",
    "hare",
    "hark",
    "harm",
    "harp",
    "hart",
    "hash",
    "hasp",
    "hast",
    "hate",
    "hath",
    "hats",
    "haul",
    "have",
    "hawk",
    "haws",
    "hays",
    "haze",
    "hazy",
    "head",
    "heal",
    "heap",
    "hear",
    "heat",
    "heck",
    "heed",
    "heel",
    "heft",
    "heil",
    "heir",
    "held",
    "hell",
    "helm",
    "help",
    "heme",
    "hemp",
    "hems",
    "hens",
    "herb",
    "herd",
    "here",
    "hero",
    "herr",
    "hers",
    "hest",
    "hewn",
    "hews",
    "hick",
    "hide",
    "hied",
    "hies",
    "high",
    "hike",
    "hill",
    "hilt",
    "hind",
    "hint",
    "hips",
    "hire",
    "hisn",
    "hiss",
    "hist",
    "hits",
    "hive",
    "hoar",
    "hoax",
    "hobo",
    "hobs",
    "hock",
    "hods",
    "hoed",
    "hoer",
    "hoes",
    "hogs",
    "hoke",
    "hold",
    "hole",
    "holt",
    "holy",
    "home",
    "homo",
    "homy",
    "hone",
    "honk",
    "hood",
    "hoof",
    "hook",
    "hoop",
    "hoot",
    "hope",
    "hopi",
    "hops",
    "hora",
    "horn",
    "hors",
    "hose",
    "hosp",
    "host",
    "hots",
    "hour",
    "hove",
    "howe",
    "howl",
    "hows",
    "hubs",
    "huck",
    "hued",
    "hues",
    "huff",
    "huge",
    "hugs",
    "hula",
    "hulk",
    "hull",
    "hump",
    "hums",
    "hung",
    "hunk",
    "huns",
    "hunt",
    "hurl",
    "hurt",
    "hush",
    "husk",
    "huts",
    "hyde",
    "hymn",
    "hype",
    "hypo",
    "iamb",
    "ibex",
    "ibid",
    "ibis",
    "icbm",
    "iced",
    "ices",
    "icky",
    "icon",
    "idea",
    "idee",
    "idem",
    "ideo",
    "ides",
    "idle",
    "idly",
    "idol",
    "idyl",
    "ieee",
    "iffy",
    "ikon",
    "ilia",
    "ilks",
    "ills",
    "illy",
    "imam",
    "imps",
    "inca",
    "inch",
    "info",
    "inks",
    "inky",
    "inly",
    "inns",
    "inst",
    "intl",
    "into",
    "intr",
    "ions",
    "iota",
    "iowa",
    "ipso",
    "iran",
    "iraq",
    "ired",
    "ires",
    "iris",
    "irks",
    "iron",
    "isis",
    "isle",
    "isms",
    "ital",
    "itch",
    "item",
    "iuds",
    "ixia",
    "izar",
    "jabs",
    "jack",
    "jade",
    "jags",
    "jail",
    "jake",
    "jamb",
    "jams",
    "jane",
    "jape",
    "jars",
    "jato",
    "java",
    "jaws",
    "jays",
    "jazz",
    "jean",
    "jeep",
    "jeer",
    "jeez",
    "jefe",
    "jell",
    "jerk",
    "jess",
    "jest",
    "jets",
    "jeux",
    "jews",
    "jibe",
    "jibs",
    "jiff",
    "jigs",
    "jill",
    "jilt",
    "jinn",
    "jins",
    "jinx",
    "jive",
    "jobs",
    "jock",
    "joes",
    "joey",
    "jogs",
    "john",
    "joie",
    "join",
    "joke",
    "jolt",
    "jose",
    "josh",
    "joss",
    "jota",
    "jots",
    "jour",
    "jowl",
    "joys",
    "juan",
    "judo",
    "judy",
    "jugs",
    "juju",
    "juke",
    "july",
    "jump",
    "june",
    "junk",
    "juno",
    "jupe",
    "jure",
    "jury",
    "just",
    "jute",
    "juts",
    "kaka",
    "kale",
    "kame",
    "kart",
    "kayo",
    "kays",
    "keel",
    "keen",
    "keep",
    "kegs",
    "kelp",
    "keno",
    "kens",
    "kent",
    "kepi",
    "kept",
    "kerb",
    "kerf",
    "kern",
    "keys",
    "khan",
    "kick",
    "kids",
    "kiev",
    "kike",
    "kill",
    "kiln",
    "kilo",
    "kilt",
    "kind",
    "kine",
    "king",
    "kink",
    "kins",
    "kips",
    "kirk",
    "kiss",
    "kist",
    "kite",
    "kith",
    "kits",
    "kiwi",
    "knee",
    "knew",
    "knit",
    "knob",
    "knot",
    "know",
    "knox",
    "koan",
    "kohl",
    "kola",
    "kong",
    "kook",
    "koto",
    "kris",
    "kudo",
    "kudu",
    "kung",
    "kwhr",
    "kyat",
    "labs",
    "lace",
    "lack",
    "lacy",
    "lade",
    "lads",
    "lady",
    "lags",
    "laid",
    "lain",
    "lair",
    "lait",
    "lake",
    "laky",
    "lama",
    "lamb",
    "lame",
    "lamp",
    "lams",
    "land",
    "lane",
    "lank",
    "laos",
    "lapp",
    "laps",
    "lard",
    "lark",
    "lash",
    "lass",
    "last",
    "late",
    "lath",
    "laud",
    "lava",
    "lave",
    "lawn",
    "laws",
    "lays",
    "laze",
    "lazy",
    "lead",
    "leaf",
    "leak",
    "leal",
    "lean",
    "leap",
    "lear",
    "leas",
    "lech",
    "lect",
    "leek",
    "leer",
    "lees",
    "left",
    "legs",
    "leis",
    "leks",
    "lend",
    "lens",
    "lent",
    "leon",
    "leos",
    "lese",
    "less",
    "lest",
    "lets",
    "leva",
    "levi",
    "levo",
    "levy",
    "lewd",
    "leys",
    "liar",
    "libs",
    "lice",
    "lick",
    "lido",
    "lids",
    "lied",
    "lief",
    "lien",
    "lier",
    "lies",
    "lieu",
    "life",
    "lift",
    "like",
    "lilt",
    "lily",
    "lima",
    "limb",
    "lime",
    "limn",
    "limo",
    "limp",
    "limy",
    "line",
    "ling",
    "link",
    "lino",
    "lins",
    "lint",
    "liny",
    "lion",
    "lips",
    "lira",
    "lire",
    "lisp",
    "list",
    "lite",
    "lith",
    "lits",
    "live",
    "load",
    "loaf",
    "loam",
    "loan",
    "lobe",
    "lobo",
    "lobs",
    "loch",
    "loci",
    "lock",
    "loco",
    "lode",
    "loft",
    "loge",
    "logo",
    "logs",
    "logy",
    "loin",
    "loll",
    "lone",
    "long",
    "look",
    "loom",
    "loon",
    "loop",
    "loos",
    "loot",
    "lope",
    "lops",
    "lord",
    "lore",
    "lorn",
    "lory",
    "lose",
    "loss",
    "lost",
    "loth",
    "lots",
    "loud",
    "loup",
    "lour",
    "lout",
    "love",
    "lows",
    "luau",
    "lube",
    "luck",
    "lucy",
    "luff",
    "luge",
    "lugs",
    "luke",
    "lull",
    "lulu",
    "lump",
    "luna",
    "lune",
    "lung",
    "lunk",
    "luny",
    "lure",
    "lurk",
    "lush",
    "lust",
    "lute",
    "luxe",
    "lyes",
    "lynx",
    "lyre",
    "mace",
    "mach",
    "mack",
    "macs",
    "made",
    "mads",
    "mage",
    "magi",
    "mags",
    "maid",
    "mail",
    "maim",
    "main",
    "make",
    "mala",
    "male",
    "mali",
    "mall",
    "malt",
    "mama",
    "mane",
    "mans",
    "manx",
    "many",
    "maps",
    "marc",
    "mare",
    "mark",
    "marl",
    "mars",
    "mart",
    "marx",
    "mary",
    "mash",
    "mask",
    "mass",
    "mast",
    "mate",
    "math",
    "mats",
    "matt",
    "maul",
    "maut",
    "maws",
    "maxi",
    "maya",
    "mayo",
    "mays",
    "maze",
    "mazy",
    "mead",
    "meal",
    "mean",
    "meas",
    "meat",
    "mech",
    "meed",
    "meek",
    "meet",
    "mein",
    "meld",
    "melt",
    "memo",
    "mend",
    "mens",
    "menu",
    "meow",
    "mere",
    "mesa",
    "mesh",
    "mess",
    "meta",
    "mete",
    "mewl",
    "mews",
    "mibs",
    "mica",
    "mice",
    "mick",
    "midi",
    "mids",
    "mien",
    "miff",
    "migs",
    "mike",
    "mild",
    "mile",
    "milk",
    "mill",
    "mils",
    "milt",
    "mime",
    "mind",
    "mine",
    "ming",
    "mini",
    "mink",
    "mins",
    "mint",
    "minx",
    "mire",
    "mirk",
    "mirv",
    "miry",
    "misc",
    "mise",
    "miso",
    "miss",
    "mist",
    "mite",
    "mitt",
    "mixt",
    "mktg",
    "moan",
    "moas",
    "moat",
    "mobs",
    "mock",
    "mode",
    "modi",
    "modo",
    "mods",
    "moil",
    "mold",
    "mole",
    "moll",
    "molt",
    "moly",
    "moms",
    "monk",
    "mono",
    "mons",
    "mony",
    "mood",
    "moon",
    "moor",
    "moos",
    "moot",
    "mope",
    "mops",
    "mopy",
    "more",
    "morn",
    "mort",
    "moss",
    "most",
    "mote",
    "moth",
    "mots",
    "moue",
    "move",
    "mown",
    "mows",
    "moxa",
    "msec",
    "much",
    "muck",
    "muds",
    "muff",
    "mugs",
    "mule",
    "mull",
    "mumm",
    "mump",
    "mums",
    "muon",
    "murk",
    "muse",
    "mush",
    "musk",
    "muss",
    "must",
    "mute",
    "mutt",
    "myna",
    "myth",
    "nabs",
    "nags",
    "naif",
    "nail",
    "name",
    "nape",
    "naps",
    "narc",
    "nard",
    "nark",
    "nary",
    "nasa",
    "natl",
    "nato",
    "naut",
    "nave",
    "navy",
    "nays",
    "nazi",
    "neap",
    "near",
    "neat",
    "nebs",
    "neck",
    "need",
    "neon",
    "nerd",
    "ness",
    "nest",
    "nets",
    "nevi",
    "news",
    "newt",
    "next",
    "nibs",
    "nice",
    "nick",
    "nigh",
    "nile",
    "nill",
    "nils",
    "nims",
    "nine",
    "nips",
    "nisi",
    "nits",
    "nixy",
    "noah",
    "nobs",
    "nock",
    "node",
    "nods",
    "noel",
    "noes",
    "nogs",
    "noir",
    "nolo",
    "nome",
    "noms",
    "none",
    "nook",
    "noon",
    "nope",
    "norm",
    "nose",
    "nosh",
    "nosy",
    "nota",
    "note",
    "nots",
    "noun",
    "nous",
    "nova",
    "novo",
    "nows",
    "nubs",
    "nude",
    "nuke",
    "null",
    "numb",
    "nuns",
    "nuts",
    "oafs",
    "oaks",
    "oars",
    "oath",
    "oats",
    "obey",
    "obis",
    "obit",
    "oboe",
    "obol",
    "odds",
    "odes",
    "odic",
    "odin",
    "odor",
    "odyl",
    "ofay",
    "offs",
    "ogee",
    "ogle",
    "ogre",
    "ohed",
    "ohio",
    "ohms",
    "oils",
    "oily",
    "oink",
    "okay",
    "okie",
    "okra",
    "olds",
    "oleo",
    "oles",
    "olio",
    "olla",
    "omen",
    "omit",
    "once",
    "ones",
    "only",
    "onto",
    "onus",
    "onyx",
    "oohs",
    "oops",
    "ooze",
    "oozy",
    "opal",
    "opec",
    "open",
    "opes",
    "opts",
    "opus",
    "oral",
    "orbs",
    "orca",
    "orch",
    "orcs",
    "ordo",
    "ores",
    "orgy",
    "orig",
    "orth",
    "orts",
    "oryx",
    "oslo",
    "otic",
    "otto",
    "ouch",
    "ours",
    "oust",
    "outs",
    "ouzo",
    "oval",
    "oven",
    "over",
    "ovid",
    "ovum",
    "owed",
    "owes",
    "owls",
    "owns",
    "oxen",
    "oxes",
    "oyer",
    "oyes",
    "oyez",
    "pace",
    "pack",
    "pacs",
    "pact",
    "pads",
    "page",
    "paid",
    "pail",
    "pain",
    "pair",
    "pale",
    "pall",
    "palm",
    "pals",
    "pane",
    "pang",
    "pans",
    "pant",
    "papa",
    "paps",
    "para",
    "pard",
    "pare",
    "park",
    "pars",
    "part",
    "paso",
    "pass",
    "past",
    "pate",
    "path",
    "pats",
    "paul",
    "pave",
    "pawl",
    "pawn",
    "paws",
    "pays",
    "peak",
    "peal",
    "pean",
    "pear",
    "peas",
    "peat",
    "peck",
    "peds",
    "peed",
    "peek",
    "peel",
    "peen",
    "peep",
    "peer",
    "pees",
    "pegs",
    "peke",
    "pelf",
    "pelt",
    "pend",
    "pens",
    "pent",
    "peon",
    "peps",
    "pere",
    "perk",
    "perm",
    "pert",
    "peru",
    "peso",
    "pest",
    "pets",
    "pews",
    "phew",
    "phiz",
    "phys",
    "pica",
    "pick",
    "pics",
    "pied",
    "pier",
    "pies",
    "pigs",
    "pike",
    "pile",
    "pill",
    "pima",
    "pimp",
    "pine",
    "ping",
    "pink",
    "pins",
    "pint",
    "piny",
    "pion",
    "pipe",
    "pips",
    "pipy",
    "pisa",
    "pish",
    "piss",
    "pita",
    "pith",
    "pits",
    "pity",
    "pius",
    "pixy",
    "pkwy",
    "plan",
    "plat",
    "play",
    "plea",
    "pled",
    "plod",
    "plop",
    "plot",
    "plow",
    "ploy",
    "plug",
    "plum",
    "plus",
    "pock",
    "poco",
    "pods",
    "poem",
    "poet",
    "poke",
    "poky",
    "pole",
    "polk",
    "poll",
    "polo",
    "pols",
    "poly",
    "pome",
    "pomp",
    "pond",
    "pone",
    "pong",
    "pons",
    "pony",
    "pooh",
    "pool",
    "poop",
    "poor",
    "pope",
    "pops",
    "pore",
    "pork",
    "porn",
    "port",
    "pose",
    "posh",
    "post",
    "posy",
    "pots",
    "pouf",
    "pour",
    "pout",
    "pows",
    "pram",
    "prat",
    "pray",
    "prep",
    "pres",
    "prey",
    "prig",
    "prim",
    "prix",
    "proc",
    "prod",
    "prof",
    "prom",
    "pron",
    "prop",
    "pros",
    "prow",
    "psst",
    "pubs",
    "puce",
    "puck",
    "puds",
    "puff",
    "pugs",
    "puke",
    "pule",
    "pull",
    "pulp",
    "puma",
    "pump",
    "punk",
    "puns",
    "punt",
    "puny",
    "pupa",
    "pups",
    "pure",
    "purl",
    "purr",
    "push",
    "puss",
    "puts",
    "putt",
    "pyre",
    "qaid",
    "qoph",
    "quad",
    "quae",
    "quag",
    "quai",
    "qual",
    "quam",
    "quat",
    "quay",
    "quem",
    "ques",
    "quey",
    "quia",
    "quid",
    "quip",
    "quit",
    "quiz",
    "quod",
    "quos",
    "race",
    "rack",
    "racy",
    "rads",
    "raft",
    "raga",
    "rage",
    "rags",
    "raid",
    "rail",
    "rain",
    "raja",
    "rake",
    "ramp",
    "rams",
    "rand",
    "rang",
    "rani",
    "rank",
    "rant",
    "rape",
    "raps",
    "rapt",
    "rara",
    "rare",
    "rase",
    "rash",
    "rasp",
    "rata",
    "rate",
    "rats",
    "rave",
    "raws",
    "rays",
    "raze",
    "razz",
    "rcpt",
    "read",
    "real",
    "ream",
    "reap",
    "rear",
    "rebs",
    "recd",
    "recs",
    "redo",
    "reds",
    "reed",
    "reef",
    "reek",
    "reel",
    "refs",
    "reft",
    "rein",
    "rely",
    "rems",
    "rend",
    "reno",
    "rent",
    "reps",
    "resp",
    "rest",
    "retd",
    "revs",
    "rhea",
    "rial",
    "ribs",
    "rice",
    "rich",
    "rick",
    "ride",
    "rids",
    "riel",
    "rife",
    "riff",
    "rift",
    "rigs",
    "rile",
    "rill",
    "rime",
    "rims",
    "rimy",
    "rind",
    "ring",
    "rink",
    "riot",
    "ripe",
    "rips",
    "rise",
    "risk",
    "rite",
    "ritz",
    "rive",
    "road",
    "roam",
    "roan",
    "roar",
    "robe",
    "robs",
    "rock",
    "rocs",
    "rode",
    "rods",
    "roes",
    "roil",
    "role",
    "roll",
    "rome",
    "romp",
    "roms",
    "rood",
    "roof",
    "rook",
    "room",
    "root",
    "rope",
    "ropy",
    "rosa",
    "rose",
    "rosy",
    "rote",
    "roto",
    "rots",
    "roue",
    "rout",
    "roux",
    "rove",
    "rows",
    "rube",
    "rubs",
    "ruby",
    "ruck",
    "rude",
    "rued",
    "ruer",
    "rues",
    "ruff",
    "rugs",
    "ruin",
    "rule",
    "rump",
    "rums",
    "rune",
    "rung",
    "runs",
    "runt",
    "ruse",
    "rush",
    "rusk",
    "rust",
    "ruth",
    "ruts",
    "ryas",
    "ryes",
    "sack",
    "sacs",
    "safe",
    "saga",
    "sage",
    "sago",
    "sags",
    "sagy",
    "said",
    "sail",
    "sake",
    "sale",
    "salt",
    "same",
    "sand",
    "sane",
    "sang",
    "sank",
    "sans",
    "saps",
    "sari",
    "sash",
    "sass",
    "sate",
    "save",
    "sawn",
    "saws",
    "says",
    "scab",
    "scad",
    "scag",
    "scam",
    "scan",
    "scar",
    "scat",
    "scil",
    "scop",
    "scot",
    "scow",
    "scud",
    "scum",
    "scut",
    "seal",
    "seam",
    "sear",
    "seas",
    "seat",
    "secs",
    "sect",
    "seed",
    "seek",
    "seem",
    "seen",
    "seep",
    "seer",
    "sees",
    "self",
    "sell",
    "semi",
    "send",
    "sent",
    "sept",
    "sera",
    "serb",
    "sere",
    "serf",
    "sets",
    "sewn",
    "sews",
    "sexy",
    "shad",
    "shag",
    "shah",
    "sham",
    "shat",
    "shay",
    "shed",
    "shes",
    "shew",
    "shim",
    "shin",
    "ship",
    "shit",
    "shiv",
    "shmo",
    "shod",
    "shoe",
    "shoo",
    "shop",
    "shot",
    "show",
    "shul",
    "shun",
    "shut",
    "siam",
    "sibs",
    "sick",
    "sics",
    "side",
    "sift",
    "sigh",
    "sign",
    "sikh",
    "silk",
    "sill",
    "silo",
    "silt",
    "simp",
    "sine",
    "sing",
    "sinh",
    "sink",
    "sins",
    "sips",
    "sire",
    "sirs",
    "site",
    "sits",
    "situ",
    "sitz",
    "size",
    "sizy",
    "skag",
    "skew",
    "skid",
    "skim",
    "skin",
    "skip",
    "skis",
    "skit",
    "skys",
    "slab",
    "slag",
    "slam",
    "slap",
    "slat",
    "slav",
    "slaw",
    "slay",
    "sled",
    "slew",
    "slid",
    "slim",
    "slip",
    "slit",
    "slob",
    "sloe",
    "slog",
    "slop",
    "slot",
    "slow",
    "slue",
    "slug",
    "slum",
    "slur",
    "slut",
    "smit",
    "smog",
    "smug",
    "smut",
    "snag",
    "snap",
    "snip",
    "snit",
    "snob",
    "snot",
    "snow",
    "snub",
    "snug",
    "soak",
    "soap",
    "soar",
    "sobs",
    "sock",
    "soda",
    "sods",
    "sofa",
    "soft",
    "soil",
    "sold",
    "sole",
    "soli",
    "solo",
    "soma",
    "some",
    "song",
    "sons",
    "soon",
    "soot",
    "soph",
    "sops",
    "sore",
    "sort",
    "sots",
    "soul",
    "soup",
    "sour",
    "sown",
    "sows",
    "soya",
    "soys",
    "span",
    "spar",
    "spas",
    "spat",
    "spay",
    "spec",
    "sped",
    "spew",
    "spic",
    "spin",
    "spit",
    "spot",
    "spry",
    "spud",
    "spun",
    "spur",
    "stab",
    "stag",
    "star",
    "stat",
    "stay",
    "stem",
    "step",
    "stet",
    "stew",
    "stir",
    "stoa",
    "stop",
    "stow",
    "stub",
    "stud",
    "stun",
    "stye",
    "styx",
    "subs",
    "such",
    "suck",
    "suds",
    "sued",
    "suer",
    "sues",
    "suet",
    "suey",
    "suez",
    "suit",
    "sulk",
    "sumo",
    "sump",
    "sums",
    "sung",
    "sunk",
    "suns",
    "supe",
    "sups",
    "supt",
    "sure",
    "surf",
    "swab",
    "swag",
    "swam",
    "swan",
    "swap",
    "swat",
    "sway",
    "swig",
    "swim",
    "swob",
    "swop",
    "swum",
    "sync",
    "syne",
    "tabs",
    "tabu",
    "tach",
    "tack",
    "taco",
    "tact",
    "tads",
    "tags",
    "tail",
    "take",
    "talc",
    "tale",
    "talk",
    "tall",
    "tame",
    "tamp",
    "tams",
    "tang",
    "tank",
    "tans",
    "taos",
    "tape",
    "taps",
    "tare",
    "tarn",
    "taro",
    "tarp",
    "tars",
    "tart",
    "task",
    "tass",
    "tate",
    "tats",
    "taut",
    "taws",
    "taxi",
    "tbsp",
    "teak",
    "teal",
    "team",
    "tear",
    "teas",
    "teat",
    "tech",
    "teds",
    "teed",
    "teem",
    "teen",
    "tees",
    "tell",
    "temp",
    "tend",
    "tens",
    "tent",
    "term",
    "tern",
    "terr",
    "test",
    "text",
    "thai",
    "than",
    "that",
    "thaw",
    "thee",
    "them",
    "then",
    "thew",
    "they",
    "thin",
    "this",
    "thor",
    "thou",
    "thro",
    "thru",
    "thud",
    "thug",
    "thus",
    "tick",
    "tics",
    "tide",
    "tidy",
    "tied",
    "tier",
    "ties",
    "tiff",
    "tike",
    "tile",
    "till",
    "tilt",
    "time",
    "tine",
    "ting",
    "tins",
    "tint",
    "tiny",
    "tipi",
    "tips",
    "tire",
    "tiro",
    "tits",
    "tnpk",
    "toad",
    "toed",
    "toes",
    "toff",
    "tofu",
    "toga",
    "togo",
    "togs",
    "toil",
    "toke",
    "told",
    "tole",
    "toll",
    "tomb",
    "tome",
    "toms",
    "tone",
    "tong",
    "tons",
    "tony",
    "took",
    "tool",
    "toot",
    "tope",
    "tops",
    "tora",
    "torc",
    "tore",
    "torn",
    "toro",
    "tors",
    "tort",
    "tory",
    "tosh",
    "toss",
    "tost",
    "tote",
    "toto",
    "tots",
    "tour",
    "tout",
    "town",
    "tows",
    "toys",
    "tram",
    "trap",
    "tray",
    "tree",
    "tref",
    "trek",
    "trey",
    "trig",
    "trim",
    "trio",
    "trip",
    "trod",
    "trop",
    "trot",
    "trow",
    "troy",
    "true",
    "tsar",
    "tuba",
    "tube",
    "tubs",
    "tuck",
    "tufa",
    "tuff",
    "tuft",
    "tugs",
    "tuna",
    "tune",
    "tuns",
    "tups",
    "turd",
    "turf",
    "turk",
    "turn",
    "tush",
    "tusk",
    "tuts",
    "tutu",
    "twas",
    "twat",
    "twig",
    "twin",
    "twit",
    "twos",
    "tyke",
    "type",
    "typo",
    "tyre",
    "tyro",
    "tzar",
    "ufos",
    "ughs",
    "ugli",
    "ugly",
    "ukes",
    "ulna",
    "ulva",
    "umps",
    "unco",
    "undo",
    "undy",
    "unit",
    "univ",
    "unix",
    "unto",
    "unum",
    "upon",
    "ural",
    "urbs",
    "urds",
    "urea",
    "urge",
    "uric",
    "urns",
    "ursa",
    "used",
    "usee",
    "user",
    "uses",
    "ussr",
    "utah",
    "vade",
    "vail",
    "vain",
    "vale",
    "vamp",
    "vane",
    "vans",
    "vary",
    "vase",
    "vast",
    "vats",
    "veal",
    "veda",
    "veep",
    "veer",
    "vees",
    "veil",
    "vein",
    "vela",
    "veld",
    "vend",
    "vent",
    "verb",
    "vers",
    "vert",
    "very",
    "vest",
    "veto",
    "vets",
    "vial",
    "vias",
    "vice",
    "vide",
    "vied",
    "vier",
    "vies",
    "view",
    "vile",
    "vims",
    "vine",
    "vino",
    "vins",
    "viny",
    "viol",
    "vips",
    "visa",
    "vise",
    "vita",
    "viva",
    "vive",
    "vivo",
    "voce",
    "void",
    "vole",
    "volt",
    "vote",
    "vows",
    "vrow",
    "vugg",
    "vugh",
    "vugs",
    "wack",
    "wacs",
    "wade",
    "wadi",
    "wads",
    "waft",
    "wage",
    "wags",
    "waif",
    "wail",
    "wain",
    "wait",
    "wake",
    "wale",
    "walk",
    "wall",
    "walt",
    "wand",
    "wane",
    "wang",
    "want",
    "ward",
    "ware",
    "wark",
    "warm",
    "warn",
    "warp",
    "wars",
    "wart",
    "wary",
    "wash",
    "wasp",
    "wast",
    "wats",
    "watt",
    "waul",
    "wave",
    "wavy",
    "waxy",
    "ways",
    "weak",
    "weal",
    "wean",
    "wear",
    "webs",
    "weds",
    "weed",
    "week",
    "ween",
    "weep",
    "weft",
    "weir",
    "weld",
    "well",
    "welt",
    "wend",
    "wens",
    "went",
    "wept",
    "were",
    "wert",
    "west",
    "wets",
    "wham",
    "whap",
    "what",
    "whee",
    "when",
    "whet",
    "whew",
    "whey",
    "whig",
    "whim",
    "whip",
    "whir",
    "whit",
    "whiz",
    "whoa",
    "whom",
    "whys",
    "wick",
    "wide",
    "wife",
    "wigs",
    "wild",
    "wile",
    "will",
    "wilt",
    "wily",
    "wind",
    "wine",
    "wing",
    "wink",
    "wino",
    "wins",
    "winy",
    "wipe",
    "wire",
    "wiry",
    "wise",
    "wish",
    "wisp",
    "with",
    "wits",
    "wive",
    "wkly",
    "woad",
    "woes",
    "woke",
    "woks",
    "wold",
    "wolf",
    "womb",
    "wont",
    "wood",
    "woof",
    "wool",
    "woos",
    "wops",
    "word",
    "wore",
    "work",
    "worm",
    "worn",
    "wort",
    "wots",
    "wove",
    "wows",
    "wrap",
    "wren",
    "writ",
    "wyes",
    "xiii",
    "xmas",
    "xvii",
    "xxii",
    "xxiv",
    "yack",
    "yaks",
    "yale",
    "yams",
    "yang",
    "yank",
    "yaps",
    "yard",
    "yare",
    "yarn",
    "yawl",
    "yawn",
    "yawp",
    "yaws",
    "yeah",
    "year",
    "yeas",
    "yegg",
    "yell",
    "yelp",
    "yens",
    "yeti",
    "yews",
    "yids",
    "yins",
    "yipe",
    "yips",
    "ymca",
    "yoga",
    "yogi",
    "yoke",
    "yolk",
    "yond",
    "yoni",
    "yore",
    "york",
    "your",
    "yowl",
    "yows",
    "yuan",
    "yuks",
    "yule",
    "yurt",
    "ywca",
    "zags",
    "zany",
    "zaps",
    "zeal",
    "zebu",
    "zeds",
    "zees",
    "zero",
    "zest",
    "zeta",
    "zeus",
    "zigs",
    "zinc",
    "zing",
    "zion",
    "zips",
    "zone",
    "zoom",
    "zoos",
    "zori",
    "zulu",
    "zuni",
]

class Pointer {
    constructor(game) {
        this.game = game;
        this.column = 0;
        this.row = 0;
    }

    gotoNextTile() {
        if (this.column < LETTER_NUMBER - 1) {
            this.column++;
        }
        return;
    }

    gotoPreviousTile() {
        if (this.column === 0) {
            return;
        } else {
            this.column--;
            return;
        }
    }

    gotoNextRow() {
        if (this.row < GUESS_NUMBER - 1) {
            this.column = 0;
            this.row++;
            game.guess.resetWord();
            toggleDatasetIsActiveRow();
        }
        return;
    }

    doBackspace() {
        if (this.column === 0) {
            return;
        } else if (!this.isEmpty()) {
            this.deleteContent();
            game.guess.updateWord();
            return;
        } else {
            this.column--;
            this.deleteContent();
            game.guess.updateWord();
            return;
        }
    }

    getHtmlElement() {
        return document.getElementById("row-" + this.row + "-column-" + this.column + "-guess"
        );
    }

    readContent() {
        return this.getHtmlElement().textContent;
    }

    isEmpty() {
        return this.readContent() === "";
    }

    writeContent(data) {
        if (!this.isEmpty()) {
            return;
        } else {
            this.getHtmlElement().textContent = data;
            this.getHtmlElement().dataset.isBlankTile = false;
            this.gotoNextTile();
            game.guess.updateWord();
            return;
        }
    }

    deleteContent() {
        this.getHtmlElement().textContent = "";
        this.getHtmlElement().dataset.isBlankTile = true;
    }

}


class Guess {
    constructor(game) {
        this.game = game;
        this.word = "";
    }

    updateWord() {
        const array = Array.from(document.getElementById("row-" + game.pointer.row).children);
        const content = array.map(div => div.textContent).join("");
        this.word = content.toLowerCase();
        return;
    }

    isValid() {
        return this.word.length == game.letterNumber;
    }

    resetWord() {
        this.word = "";
    }


    processGuess() {
        if (game.pointer.isEmpty()) {
            invalidSubmission("Not enough letters!")
            return;
        }
        else if (!WORDS.includes(game.guess.word)) {
            invalidSubmission("Not in the dictionary!");
            return;
        }
        else if (game.pointer.row == (game.guessNumber - 1) && game.guess.word != game.answer) {
            toggleDatasetIsActiveRow();
            colorScoreModule();
            gameOver();
            return;
        }
        else if (correctGuessAtTurn(0)) {
            toggleDatasetIsActiveRow();
            correctGuess("That was hell of a guess!")
            return;
        }
        else if (correctGuessAtTurn(1, 3)) {
            toggleDatasetIsActiveRow();
            correctGuess("Magnificient!")
            return;
        }
        else if (correctGuessAtTurn(4)) {
            toggleDatasetIsActiveRow();
            correctGuess("Good!")
            return;
        }
        else if (correctGuessAtTurn(5)) {
            toggleDatasetIsActiveRow();
            correctGuess("Phew!")
            return;
        }
        else {
            toggleDatasetIsActiveRow();
            colorScoreModule();
            game.pointer.gotoNextRow();
            return;
        }
    }
}

class Keyboard {
    constructor(game) {
        this.game = game;
        document.addEventListener("keydown", this.processPhysicalKeyboardPress);
    }

    processPhysicalKeyboardPress(e) {
        if (e.key === "Enter") {
            // processGuess();
            game.guess.processGuess();
            return;
        }

        if (e.key === "Backspace" || e.key === "Delete") {
            game.pointer.doBackspace();
            return;
        }

        if (e.key.match(/^[A-Za-z]$/)) {
            growTiles();
            game.pointer.writeContent(e.key);
            return;
        }
    }

}


class OnscreenKeyboard {
    constructor(game) {
        this.game = game;
        this.keyboard = document.getElementById("onscreen-keyboard");
        this.onscreenKeyboardSwitch = new AbortController();
        this.activateOnscreenKeyboard();
    }

    activateOnscreenKeyboard() {
        // this.keyboard.addEventListener("click", location.reload);
        this.keyboard.addEventListener(
            "click",
            (event) => {
                if (event.target.className === "keyboard-button") {
                    // let key = event.target.textContent;
                    let key = event.target.dataset.key;
                    this.handleOnscreenKeyboardClick(key);
                }
            },
            {
                signal: this.onscreenKeyboardSwitch.signal,
            }
        );
    }


    handleOnscreenKeyboardClick(e) {
        if (e === "delete") {
            game.pointer.doBackspace();
            document.activeElement.blur(); //important
            return;
        } else if (e === "enter") {
            // processGuess();
            game.guess.processGuess();
            document.activeElement.blur();
            return;
        }else if (e === "restart") {
            location.reload();
        } else {
            growTiles();
            game.pointer.writeContent(e);
            document.activeElement.blur();
            return;
        }
    }


}


class Game {
    constructor(letterNumber = 4, guessNumber = 6) {
        this.letterNumber = letterNumber;
        this.guessNumber = guessNumber;
        this.answer = WORDS[Math.floor(Math.random() * WORDS.length)];
        this.pointer = new Pointer(this);
        this.guess = new Guess(this);
        this.keyboard = new Keyboard(this);
        this.onscreenKeyboard = new OnscreenKeyboard(this);
    }

    startInteraction() {
        // document.addEventListener("keydown", processPhysicalKeyboardPress);
        // this.keyboard.
        return;
    }

    stopInteraction() {
        document.removeEventListener("keydown", this.keyboard.processPhysicalKeyboardPress);
        // document.getElementsByClassName("keyboard-button")
        // this.keyboardSwitch.abort();
        return;
    }
}

createDomElements();
const game = new Game();





function invalidSubmission(message) {
    processMessageBox(message);
    setMessageBoxTimer();
    animateTiles("shake");
    return;
}

function processMessageBox(message) {
    var messageBox = document.getElementById("message-box");
    messageBox.textContent = message;
    messageBox.style.visibility = "visible";
    return;
}

function setMessageBoxTimer(duration = 1500) {
    setTimeout(() => {
        toggleMessageBox();
    }, 1500);
    return;
}

function toggleMessageBox() {
    var messageBox = document.getElementById("message-box");
    messageBox.style.visibility = "hidden";
    return;
}

function animateTiles(style) {
    const array = Array.from(document.getElementById("row-" + game.pointer.row + "-guess").children);
    array.forEach((tile) => {
        tile.classList.add(style);
        tile.addEventListener(
            "animationend",
            () => {
                tile.classList.remove(style);
                // tile.dataset.animation =
            }, {
            once: true,
        }
        );
    });
}


function growTiles() {
    const tile = document.getElementById("row-" + game.pointer.row + "-column-" + game.pointer.column + "-guess");
    tile.classList.add("grow-and-shrink");
    tile.addEventListener(
        "animationend",
        () => {
            tile.classList.remove("grow-and-shrink");
            // tile.dataset.animation =
        }, {
        once: true,
    }
    );

}


function toggleDatasetIsActiveRow() {
    const row = document.getElementById("row-" + game.pointer.row);
    if (row.dataset.isActiveRow == "true") {
        row.dataset.isActiveRow = "false";
    }
    else {
        row.dataset.isActiveRow = "true";
    }
    return;
}


function correctGuessAtTurn(lowerRowNumber, higherRowNumber = lowerRowNumber) {
    return (game.guess.word === game.answer && game.pointer.row >= lowerRowNumber && game.pointer.row <= higherRowNumber)
}


function processGuessLetters() {
    const n = game.answer.length;
    var word = game.answer;
    var tempGuess = game.guess.word;
    var colors = Array(n).fill(0);
    // console.log(tempGuess);
    for (let i = 0; i < n; i++) {
        if (tempGuess[i] === word[i]) {
            colors[i] = 2;
            word = word.replace(tempGuess[i], " ");
        }
    }
    for (let i = 0; i < n; i++) {
        if (colors[i] !== 2 && word.includes(tempGuess[i])) {
            colors[i] = 1;
            word = word.replace(tempGuess[i], " ");
        }
    }
    // console.log(colors);
    return colors;
}



function colorScoreModule() {
    const colors = { 2: "green", 1: "yellow", 0: "dark-gray" };
    // d = a.map(function(item) {return c[item]})
    const processedLetters = processGuessLetters();
    console.log(processedLetters);
    const convertedLetters = processedLetters.map(function (item) { return colors[item] }).sort().reverse();
    console.log(convertedLetters);
    convertedLetters.forEach((color, index) => {
        var square = getScoreTileFromCurrentRow(index);
        square.classList.add(color);
    });
    return;
}



function getScoreTileFromCurrentRow(columnNumber) {
    return document.getElementById(
        "row-" + game.pointer.row + "-column-" + columnNumber + "-score"
    );
}


function correctGuess(message) {
    colorScoreModule();
    processMessageBox(message);
    animateTiles("dance");
    game.stopInteraction();
    silenceKeyboard();
    return;
}




function gameOver() {
    processMessageBox(game.answer)
    game.stopInteraction();
    // game.keyboardSwitch.abort();
    silenceKeyboard();
    return;
}


















// The following builds all the necessary HTML elements.
function createDomElements() {
    createMainContainerDiv();
    createHeaderDiv("Word Master");
    createGameContainerDiv("game-container");
    createMessageBoxDiv("message-box");
    createBoardWrapperDiv("board-wrapper");
    createBoardContainerDiv("board");
    createOnscreenKeyboardDiv("onscreen-keyboard");
    createBoardRows();
    createOnscreenKeyboard();
}

function createMainContainerDiv() {
    const mainContainer = document.createElement("div");
    mainContainer.setAttribute("id", "main-container");
    document.body.append(mainContainer);
    return;
}

function createHeaderDiv(gameTitle) {
    const headerDiv = document.createElement("div");
    headerDiv.setAttribute("id", "header");
    // headerDiv.classList.add("header");
    const header = document.createElement("h1");
    headerText = document.createTextNode(gameTitle);
    header.appendChild(headerText);
    headerDiv.appendChild(header);
    document.getElementById("main-container").append(headerDiv);
    // document.body.append(header);
    return;
}

function createGameContainerDiv(divId) {
    const gameContainer = document.createElement("div");
    gameContainer.setAttribute("id", divId);
    // gameContainer.classList.add("game-container");
    document.getElementById("main-container").append(gameContainer);
    // document.body.append(gameContainer);
    return;
}

function createMessageBoxDiv(divId) {
    const gameContainer = document.getElementById("game-container");
    const messageBoxContainer = document.createElement("div");
    messageBoxContainer.setAttribute("id", divId);
    messageBoxContainer.textContent = ("I am a toast!")
    gameContainer.append(messageBoxContainer);
    return;
}

function createBoardWrapperDiv(divId) {
    const gameContainer = document.getElementById("game-container");
    const boardWrapper = document.createElement("div");
    boardWrapper.setAttribute("id", divId);
    // boardWrapper.classList.add("board-wrapper");
    gameContainer.append(boardWrapper);
    return;
}

function createBoardContainerDiv(divId) {
    const boardWrapper = document.getElementById("board-wrapper");
    const board = document.createElement("div");
    board.setAttribute("id", divId);
    // board.classList.add("board");
    boardWrapper.append(board);
    return;
}

function createOnscreenKeyboardDiv(divId) {
    const gameContainer = document.getElementById("game-container");
    const onscreenKeyboard = document.createElement("div");
    onscreenKeyboard.setAttribute("id", divId);
    onscreenKeyboard.classList.add("keyboard");
    gameContainer.append(onscreenKeyboard);
    return;
}

function createBoardRows() {
    const board = document.getElementById("board");

    for (let rowIndex = 0; rowIndex < GUESS_NUMBER; rowIndex++) {
        const row = document.createElement("div");
        row.setAttribute("id", "row-" + rowIndex);
        row.dataset.isActiveRow = "false";
        row.classList.add("board-row");
        board.append(row);

        const guess = document.createElement("div");
        guess.setAttribute("id", "row-" + rowIndex + "-guess");
        guess.classList.add("guess-module");
        const score = document.createElement("div");
        score.setAttribute("id", "row-" + rowIndex + "-score");
        score.classList.add("score-module");
        row.append(guess, score);

        for (
            let columnIndex = 0; columnIndex < LETTER_NUMBER; columnIndex++
        ) {
            const guessElement = document.createElement("div");
            const scoreElement = document.createElement("div");

            guessElement.setAttribute("id", "row-" + rowIndex + "-column-" + columnIndex + "-guess");
            guessElement.classList.add("guess-element");
            guessElement.textContent = "";
            guessElement.dataset.isBlankTile = "true";
            guess.append(guessElement);

            scoreElement.setAttribute("id", "row-" + rowIndex + "-column-" + columnIndex + "-score");
            scoreElement.classList.add("score-element");
            score.append(scoreElement);
        }
    }
    document.getElementById("row-0").dataset.isActiveRow = "true";
    return;
}

// function toggleDatasetIsActiveRow() {
//     const row = document.getElementById("row-index-" + game.pointer.row);
//     if (row.dataset.isActiveRow == "true") {
//         row.dataset.isActiveRow = "false";
//     }
//     else {
//         row.dataset.isActiveRow = "true";
//     }
//     return;
// }


function createOnscreenKeyboard() {
    const keyboard = document.getElementById("onscreen-keyboard");
    
    // const set0 = new Set(["?", "a", "b", "c", "d", "e", "f", "g", "h", "i",]);
    // const set1 = new Set(["restart", "j", "k", "l", "m", "n", "o", "p", "q", "r",]);
    // const set2 = new Set(["enter", "s", "t", "u", "v", "w", "x", "y", "z", "delete",]);
    
    
    const set0 = new Set(["q", "w", "e", "r", "t", "y", "u", "i", "o", "p",]);
    const set1 = new Set(["a", "s", "d", "f", "g", "h", "j", "k", "l",]);
    const set2 = new Set(["enter", "z", "x", "c", "v", "b", "n", "m", "delete"]);


    for (let index = 0; index < 3; index++) {
        let div = document.createElement("div");
        div.setAttribute("id", "keyboard-row-" + index);
        div.classList.add("keyboard-row");
        keyboard.append(div);
    }

    const row0 = document.getElementById("keyboard-row-0");
    const row1 = document.getElementById("keyboard-row-1");
    const row2 = document.getElementById("keyboard-row-2");

    function createButton(setNum, rowNum) {
        setNum.forEach((key) => {
            const buttonElement = document.createElement("button");
            buttonElement.textContent = key;
            buttonElement.setAttribute("id", key);
            buttonElement.classList.add("keyboard-button");
            // buttonElement.dataset.state = "neutral";
            buttonElement.dataset.key = key;
            rowNum.append(buttonElement);
        });
    }

    createButton(set0, row0);
    createButton(set1, row1);
    createButton(set2, row2);

    document.getElementById("enter").innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24"><path d="M19,6a1,1,0,0,0-1,1v4a1,1,0,0,1-1,1H7.41l1.3-1.29A1,1,0,0,0,7.29,9.29l-3,3a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l3,3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L7.41,14H17a3,3,0,0,0,3-3V7A1,1,0,0,0,19,6Z"/></svg>';


    document.getElementById("delete").innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"> <path d="M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.9.89 1.59.89h15c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H7.07L2.4 12l4.66-7H22v14zm-11.59-2L14 13.41 17.59 17 19 15.59 15.41 12 19 8.41 17.59 7 14 10.59 10.41 7 9 8.41 12.59 12 9 15.59z"></path></svg>';

    // document.getElementById("restart").innerHTML = '<svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="M19.146 4.854l-1.489 1.489A8 8 0 1 0 12 20a8.094 8.094 0 0 0 7.371-4.886 1 1 0 1 0-1.842-.779A6.071 6.071 0 0 1 12 18a6 6 0 1 1 4.243-10.243l-1.39 1.39a.5.5 0 0 0 .354.854H19.5A.5.5 0 0 0 20 9.5V5.207a.5.5 0 0 0-.854-.353z"/> </svg>';


    let spacer1 = document.createElement("div");
    spacer1.classList.add("spacer");
    document.getElementById("keyboard-row-1").prepend(spacer1)

    let spacer2 = document.createElement("div");
    spacer2.classList.add("spacer");
    document.getElementById("keyboard-row-1").appendChild(spacer2)
    return;
}



